# Generated by Django 2.2.5 on 2019-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_url', models.CharField(max_length=50)),
                ('original_url', models.TextField()),
            ],
        ),
    ]
